import { readFile, writeFile } from "node:fs/promises";

const source = new URL("../docs/prompts/monku-fusion-engine-2026-09-26.md", import.meta.url);
const target = new URL("../shared/fusion-prompt.ts", import.meta.url);
const constitutionSource = new URL("../docs/prompts/monku-ai-constitution-v1.0.md", import.meta.url);
const constitutionTarget = new URL("../shared/monku-constitution.ts", import.meta.url);
const escapeTemplateLiteral = (value) =>
  value.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const document = await readFile(source, "utf8");
const suffix = "# INPUT\n\n{{text}}\n";
if (!document.endsWith(suffix) || document.split("{{text}}").length !== 2) {
  throw new Error("Expected exactly one trailing INPUT placeholder");
}
const instructions = document.slice(0, -suffix.length).trimEnd();
await writeFile(target, '// Generated by scripts/sync-prompt.mjs from the approved prompt document.\n// Edit the document, then run npm run prompt:sync.\nexport const FUSION_INSTRUCTIONS = `' + escapeTemplateLiteral(instructions) + '`;\n');

const constitutionDocument = await readFile(constitutionSource, "utf8");
const constitutionHeading = "## 存在の定義と基本姿勢";
const constitutionStart = constitutionDocument.indexOf(constitutionHeading);
if (!constitutionDocument.startsWith("# Monku_AI Constitution\n") || constitutionStart < 0) {
  throw new Error("Expected the adopted Monku_AI Constitution v1.0 snapshot");
}
const constitutionInstructions =
  "# Monku_AI Constitution\n\n" + constitutionDocument.slice(constitutionStart).trimEnd();
await writeFile(
  constitutionTarget,
  '// Generated by scripts/sync-prompt.mjs from the adopted Monku_AI Constitution v1.0 snapshot.\n// Edit the common original, adopt a new snapshot, then run npm run prompt:sync.\nexport const MONKU_AI_CONSTITUTION = `' + escapeTemplateLiteral(constitutionInstructions) + '`;\n',
);
